//
//  Data.swift
//  GeekQuestions
//
//  Created by Lucas Real Dias on 10/05/23.
//

import Foundation

struct Anwser {
    let text: String
    var correct: Bool = false
}

struct Questions {
    let question : String
    let alternatives : [Anwser]

    init(question: String, alternatives : [Anwser]) {
        self.question = question
        self.alternatives = alternatives.shuffled()
    }
}

var questions: [Questions] = [ // 65 questions

    Questions(question: "Qual a bebida preferida do Kel da série Kennan e Kel?",
              alternatives: [Anwser(text: "Suco de uva"),
                             Anwser(text: "Cerveja"),
                             Anwser(text: "Agua tônica"),
                             Anwser(text: "Refrigerante de laranja", correct: true),
                             Anwser(text: "Suco de tomate")]),

    Questions(question: "Qual dos animes abaixo foi desenvolvido pelos estúdios Ghibli?",
              alternatives: [Anwser(text: "A Viagem de Chihiro", correct: true),
                             Anwser(text: "Shaman King"),
                             Anwser(text: "Naruto"),
                             Anwser(text: "Death Note"),
                             Anwser(text: "Inu Yasha")]),

    Questions(question: "Quem é o autor de O Senhor dos Anéis?",
              alternatives: [Anwser(text: "Bram Stoker"),
                             Anwser(text: "H. G. Wells"),
                             Anwser(text: "Júlio Verne"),
                             Anwser(text: "António Nunes"),
                             Anwser(text: "J. R. R. Tolkien", correct: true)]),

    Questions(question: "Qual é o nome do jogo de cartas jogado em Yu-Gi-Oh!?",
              alternatives: [Anwser(text: "Magic: The Gathering"),
                             Anwser(text: "Duel Monsters", correct: true),
                             Anwser(text: "Pokémon TCG "),
                             Anwser(text: "World of Warcraft TCG"),
                             Anwser(text: "Yu-Gi-Oh! TCG")]),

    Questions(question: "Qual o nome da personagem principal da série de jogos Tomb Raider?",
              alternatives: [Anwser(text: "Sam Nishimura"),
                             Anwser(text: "Kurtis Trent"),
                             Anwser(text: "Lara Croft", correct: true),
                             Anwser(text: "Amanda Evert"),
                             Anwser(text: "Jacob")]),

    Questions(question: "Qual o nome do personagem principal da série de jogos God of War?",
              alternatives: [Anwser(text: "Hades"),
                             Anwser(text: "Ares"),
                             Anwser(text: "Zeus"),
                             Anwser(text: "Atreus"),
                             Anwser(text: "Kratos", correct: true)]),

    Questions(question: "Qual o nome do personagem principal da série de jogos Uncharted?",
              alternatives: [Anwser(text: "Luck Sterblich"),
                             Anwser(text: "The Rock"),
                             Anwser(text: "Henry James"),
                             Anwser(text: "Victor Sullivan"),
                             Anwser(text: "Nathan Drake", correct: true)]),

    Questions(question: "Qual dos jogos a seguir não é um jogo de corrida?",
              alternatives: [Anwser(text: "Gran Turismo"),
                             Anwser(text: "Driver"),
                             Anwser(text: "Need for Speed"),
                             Anwser(text: "Forza Motorsport"),
                             Anwser(text: "Alan Wake", correct: true)]),

    Questions(question: "O mestre dos mangás Junji Ito ficou conhecido pelas suas obras de:",
              alternatives: [Anwser(text: "Comédia"),
                             Anwser(text: "Romance"),
                             Anwser(text: "Ação"),
                             Anwser(text: "Aventura"),
                             Anwser(text: "Horror", correct: true)]),

    Questions(question: "Qual o nome do super-herói interpretado pelo Chaves?",
              alternatives: [Anwser(text: "Super Chaves"),
                             Anwser(text: "El Chavo"),
                             Anwser(text: "Super Chavo"),
                             Anwser(text: "Capitão Linguiça"),
                             Anwser(text: "Chapolim Colorado", correct: true)]),

    Questions(question: "Qual a comida preferida do Chaves?",
              alternatives: [Anwser(text: "Lasanha"),
                             Anwser(text: "Churros"),
                             Anwser(text: "Churrasco"),
                             Anwser(text: "Saunduíche de Pernil"),
                             Anwser(text: "Sanduíche de Presunto", correct: true)]),

    Questions(question: "Qual dos jogos abaixo não pertence a franquia Souls?",
              alternatives: [Anwser(text: "Dark Souls 3"),
                             Anwser(text: "Elden Ring"),
                             Anwser(text: "Dark Souls"),
                             Anwser(text: "Demon's Souls"),
                             Anwser(text: "Bloodborn", correct: true)]),

    Questions(question: "Qual o nome da atriz que interpreta Eleven em Stranger Things?",
              alternatives: [Anwser(text: "Megan Fox"),
                             Anwser(text: "Palmirinha"),
                             Anwser(text: "Adriana Esteves"),
                             Anwser(text: "Emma Stone"),
                             Anwser(text: "Millie Bobby Brown", correct: true)]),

    Questions(question: "Qual o nome da atriz que interpreta Wandinha na série da Netflix?",
              alternatives: [Anwser(text: "Paolla Oliveira"),
                             Anwser(text: "Emma Myers"),
                             Anwser(text: "Bella Ramsey"),
                             Anwser(text: "Anna Torv"),
                             Anwser(text: "Jenna Ortega", correct: true)]),

    Questions(question: "Qual o ponto fraco do Super-Homem?",
              alternatives: [Anwser(text: "Diamante"),
                             Anwser(text: "Cobre"),
                             Anwser(text: "Agua"),
                             Anwser(text: "Lava"),
                             Anwser(text: "Kryptonita", correct: true)]),

    Questions(question: "Qualo nome do planeta natal do personagem Spock em Star Trek?",
              alternatives: [Anwser(text: "Ferenginar"),
                             Anwser(text: "Qo'noS"),
                             Anwser(text: "Romulus"),
                             Anwser(text: "Andoria"),
                             Anwser(text: "Vulcano", correct: true)]),

    Questions(question: "Qual o nome da criatura lendária que é a mascote em Final Fantasy?",
              alternatives: [Anwser(text: "Tonberry"),
                             Anwser(text: "Cactuar"),
                             Anwser(text: "Moogle"),
                             Anwser(text: "Behemoth"),
                             Anwser(text: "Chocobo", correct: true)]),

    Questions(question: "Qual o nome da nave pilotada por Han Solo e Chewbacca em Star Wars?",
              alternatives: [Anwser(text: "IE Fighter"),
                             Anwser(text: "X-Wing"),
                             Anwser(text: "Star Destroyer"),
                             Anwser(text: "Death Star"),
                             Anwser(text: "Millennium Falcon", correct: true)]),

    Questions(question: "Em qual dos consoles abaixo foi lançado o game Super Mario World?",
              alternatives: [Anwser(text: "Xbox 360"),
                             Anwser(text: "Playstation 1"),
                             Anwser(text: "Nintendo Wii"),
                             Anwser(text: "Nintendo 64"),
                             Anwser(text: "Super Nintendo", correct: true)]),

    Questions(question: "Qual é o nome do personagem principal dos livros Crônicas de Gelo e Fogo?",
              alternatives: [Anwser(text: "Tonberry"),
                             Anwser(text: "Tyrion Lannister"),
                             Anwser(text: "Cersei Lannister"),
                             Anwser(text: "Bran Stark"),
                             Anwser(text: "Jon Snow", correct: true)]),

    Questions(question: "O jogo Dungeons e Dragon é um:",
              alternatives: [Anwser(text: "MMORPG"),
                             Anwser(text: "FPS"),
                             Anwser(text: "MOBA"),
                             Anwser(text: "TCG"),
                             Anwser(text: "RPG de Mesa", correct: true)]),

    Questions(question: "Qual o nome de umas das armas mais famosas do jogo Counter Strike?",
              alternatives: [Anwser(text: "AK37"),
                             Anwser(text: "AK77"),
                             Anwser(text: "AK44"),
                             Anwser(text: "AK74"),
                             Anwser(text: "AK47", correct: true)]),

    Questions(question: "Qual o nome do jogo de luta criado pela SNK, que teve sua estreia em 1994?",
              alternatives: [Anwser(text: "Street Fighter"),
                             Anwser(text: "Mortal Kombat"),
                             Anwser(text: "Virtua Fighter"),
                             Anwser(text: "Tekken"),
                             Anwser(text: "King of Fighters", correct: true)]),

    Questions(question: "Qual o nome do planeta natal da personagem Gamora em Guardiões da Galáxia?",
              alternatives: [Anwser(text: "Xandar"),
                             Anwser(text: "Knowhere"),
                             Anwser(text: "Contraxia"),
                             Anwser(text: "Sovereign"),
                             Anwser(text: "Zen-Whoberi", correct: true)]),

    Questions(question: "Qual o nome do personagem que é considerado o maior vilão em Star Trek?",
              alternatives: [Anwser(text: "Q"),
                             Anwser(text: "The Borg Queen"),
                             Anwser(text: "Gul Dukat"),
                             Anwser(text: "Emperor Palpatine"),
                             Anwser(text: "Khan Noonien Singh", correct: true)]),

    Questions(question: "Qual o nome do Shinigami que acompanha Light Yagami em Death Note?",
              alternatives: [Anwser(text: "Tandherium"),
                             Anwser(text: "Ryuga"),
                             Anwser(text: "Goolard"),
                             Anwser(text: "Baphomet"),
                             Anwser(text: "Ryuk", correct: true)]),

    Questions(question: "Qual o nome da espada mágica de Guts na série de mangá e anime Berserk?",
              alternatives: [Anwser(text: "Excalibur"),
                             Anwser(text: "Masamune"),
                             Anwser(text: "Muramasa"),
                             Anwser(text: "Kusanagi"),
                             Anwser(text: "Dragon Slayer", correct: true)]),

    Questions(question: "One Piece é um anime de?",
              alternatives: [Anwser(text: "Terror"),
                             Anwser(text: "Corrida"),
                             Anwser(text: "Guerreiros Medievais"),
                             Anwser(text: "Robôs"),
                             Anwser(text: "Piratas", correct: true)]),

    Questions(question: "Qual o autor de It - A Coisa?",
              alternatives: [Anwser(text: "Anne Rice"),
                             Anwser(text: "Mary Shelley"),
                             Anwser(text: "H. P. Lovecraft"),
                             Anwser(text: "Edgar Allan Poe"),
                             Anwser(text: "Stephen King", correct: true)]),

    Questions(question: "Qual das cidades abaixo pertence ao universo de Ragnarok Online?",
              alternatives: [Anwser(text: "Argatha"),
                             Anwser(text: "Akakor"),
                             Anwser(text: "Alba"),
                             Anwser(text: "Atlântida"),
                             Anwser(text: "Prontera", correct: true)]),

    Questions(question: "Os Humanos em World of Warcraf pertencem a qual facção?",
              alternatives: [Anwser(text: "Ferrápios"),
                             Anwser(text: "Guálapagos"),
                             Anwser(text: "Alienígenas"),
                             Anwser(text: "Horda"),
                             Anwser(text: "Aliança", correct: true)]),

    Questions(question: "Qual o gênero de Prison Tale, um dos primeiros jogos online para PC?",
              alternatives: [Anwser(text: "Tabuleiro"),
                             Anwser(text: "RPG"),
                             Anwser(text: "MOBA"),
                             Anwser(text: "FPS"),
                             Anwser(text: "MMORPG", correct: true)]),

    Questions(question: "Qual dos terrenos abaixo não pertence ao jogo de cartas Magic: The Gathering?",
              alternatives: [Anwser(text: "Ilha"),
                             Anwser(text: "Planíce"),
                             Anwser(text: "Pântano"),
                             Anwser(text: "Montanha"),
                             Anwser(text: "Lunar", correct: true)]),

    Questions(question: "Qual o verdadeiro nome do Homem-Aranha?",
              alternatives: [Anwser(text: "Tommy Shelby"),
                             Anwser(text: "Mario Bros"),
                             Anwser(text: "Jack Sparrow"),
                             Anwser(text: "Pedro Stwart"),
                             Anwser(text: "Peter Parker", correct: true)]),

    Questions(question: "Qual o nome da príncesa que Mario tenta resgatar durante seus jogos?",
              alternatives: [Anwser(text: "Xuxa"),
                             Anwser(text: "Safíra"),
                             Anwser(text: "Rubi"),
                             Anwser(text: "Pearl"),
                             Anwser(text: "Peach", correct: true)]),

    Questions(question: "Os Orcs em World of Warcraf pertencem a qual facção?",
              alternatives: [Anwser(text: "Ferrantes"),
                             Anwser(text: "Marrápios"),
                             Anwser(text: "Alienígenas"),
                             Anwser(text: "Aliança"),
                             Anwser(text: "Horda", correct: true)]),

    Questions(question: "A música de fundo do App faz referência a qual game?",
              alternatives: [Anwser(text: "Dofus"),
                             Anwser(text: "Minecraft"),
                             Anwser(text: "Halo"),
                             Anwser(text: "Gears of War"),
                             Anwser(text: "Top Gear", correct: true)]),

    Questions(question: "Qual o nome do robô gigante dos Power Rangers?",
              alternatives: [Anwser(text: "Machine Learning"),
                             Anwser(text: "Travolta"),
                             Anwser(text: "Super Kill"),
                             Anwser(text: "Transformers"),
                             Anwser(text: "Megazord", correct: true)]),

    Questions(question: "Qual dos jogos abaixo é um exclusivo da Microsoft?",
              alternatives: [Anwser(text: "The Sims"),
                             Anwser(text: "God of War"),
                             Anwser(text: "Ragnarok Online"),
                             Anwser(text: "Grand Chase"),
                             Anwser(text: "Gears of War", correct: true)]),

    Questions(question: "A empresa que detém a propriedade do Batman é:",
              alternatives: [Anwser(text: "Netflix"),
                             Anwser(text: "Globo"),
                             Anwser(text: "CD"),
                             Anwser(text: "Marvel"),
                             Anwser(text: "DC", correct: true)]),

    Questions(question: "Qual o nome da empresa de sistemas aeroespaciais de Elon Musk?",
              alternatives: [Anwser(text: "Fahren"),
                             Anwser(text: "Moonlight"),
                             Anwser(text: "NASA"),
                             Anwser(text: "Alliance"),
                             Anwser(text: "SpaceX", correct: true)]),

    Questions(question: "Qual o nome do maior vilão em O Senhor dos Anéis?",
              alternatives: [Anwser(text: "Bilbo"),
                             Anwser(text: "Frodo"),
                             Anwser(text: "Skyller"),
                             Anwser(text: "Bauroth"),
                             Anwser(text: "Sauron", correct: true)]),

    Questions(question: "Quem foi o chefe da ordem dos magos em O Senhor dos Anéis?",
              alternatives: [Anwser(text: "Peregrin Took"),
                             Anwser(text: "Legolas"),
                             Anwser(text: "Gollum"),
                             Anwser(text: "Gandalf"),
                             Anwser(text: "Saruman", correct: true)]),

    Questions(question: "Quem foi o criador do jogo de cartas Magic: The Gathering?",
              alternatives: [Anwser(text: "Gerald Hoffman"),
                             Anwser(text: "Lucas Neil"),
                             Anwser(text: "R. L. Sullivan"),
                             Anwser(text: "Paul Nickel"),
                             Anwser(text: "Richard Garfield", correct: true)]),

    Questions(question: "Qual o nome do Dragão de O Hobbit?",
              alternatives: [Anwser(text: "Haug"),
                             Anwser(text: "Thanderius"),
                             Anwser(text: "Gil de Ham"),
                             Anwser(text: "Godzilla"),
                             Anwser(text: "Smaug", correct: true)]),

    Questions(question: "Qual o nome verdadeiro de Heisenberg em Breaking Bad?",
              alternatives: [Anwser(text: "Curry"),
                             Anwser(text: "Julian"),
                             Anwser(text: "Ronaldo"),
                             Anwser(text: "Michael"),
                             Anwser(text: "Walter", correct: true)]),

    Questions(question: "Quem era o valentão da escola em Todo Mundo Odeia o Chris?",
              alternatives: [Anwser(text: "Fred"),
                             Anwser(text: "Julius"),
                             Anwser(text: "Malcon"),
                             Anwser(text: "Jack"),
                             Anwser(text: "Caruso", correct: true)]),

    Questions(question: "Quando foi lançado o filme E.T. O Extraterrestre?",
              alternatives: [Anwser(text: "2013"),
                             Anwser(text: "1995"),
                             Anwser(text: "1980"),
                             Anwser(text: "1977"),
                             Anwser(text: "1982", correct: true)]),

    Questions(question: "Qual o nome da bola do filme Náufrago?",
              alternatives: [Anwser(text: "Nollan"),
                             Anwser(text: "Lilith"),
                             Anwser(text: "Cláudio"),
                             Anwser(text: "Peterson"),
                             Anwser(text: "Wilson", correct: true)]),

    Questions(question: "Qual dos personagens abaixo não faz parte da franquia Resident Evil?",
              alternatives: [Anwser(text: "Albert Wesker"),
                             Anwser(text: "Nemesis"),
                             Anwser(text: "Chris Redfield"),
                             Anwser(text: "Lisa Trevor"),
                             Anwser(text: "Honda Bram", correct: true)]),

    Questions(question: "Quem é a esposa de Gomez Addams, da Família Addams?",
              alternatives: [Anwser(text: "Anastácia Addams"),
                             Anwser(text: "Angela Addams"),
                             Anwser(text: "Néia Addams"),
                             Anwser(text: "Maria Addams"),
                             Anwser(text: "Mortícia Addams", correct: true)]),

    Questions(question: "Em que ano foi lançado o primeiro filme da saga Harry Potter?",
              alternatives: [Anwser(text: "2002"),
                             Anwser(text: "2003"),
                             Anwser(text: "1998"),
                             Anwser(text: "2000"),
                             Anwser(text: "2001", correct: true)]),

    Questions(question: "Qual game ganhou o Game Awards 2020?",
              alternatives: [Anwser(text: "League of Legends"),
                             Anwser(text: "Valorant"),
                             Anwser(text: "Dishonored"),
                             Anwser(text: "Deathloop"),
                             Anwser(text: "The Last of Us 2", correct: true)]),

    Questions(question: "Quando o game Super Mario Bros foi lançado?",
              alternatives: [Anwser(text: "1984"),
                             Anwser(text: "2010"),
                             Anwser(text: "2000"),
                             Anwser(text: "1988"),
                             Anwser(text: "1985", correct: true)]),

    Questions(question: "Qual o nome verdadeiro do Batman?",
              alternatives: [Anwser(text: "Bruce Willis"),
                             Anwser(text: "Jack Michael"),
                             Anwser(text: "Allen Murph"),
                             Anwser(text: "Phill Spencer"),
                             Anwser(text: "Bruce Wayne", correct: true)]),

    Questions(question: "Qual o nome do automóvel utilizado por Batman?",
              alternatives: [Anwser(text: "Batmobile"),
                             Anwser(text: "Batspeed"),
                             Anwser(text: "Carbat"),
                             Anwser(text: "Batcar"),
                             Anwser(text: "Batmóvel", correct: true)]),

    Questions(question: "Os Orcs em World of Warcraf pertencem a qual facção?",
              alternatives: [Anwser(text: "Ferrantes"),
                             Anwser(text: "Marrápios"),
                             Anwser(text: "Alienígenas"),
                             Anwser(text: "Aliança"),
                             Anwser(text: "Horda", correct: true)]),

    Questions(question: "O vilão Coringa apareceu pela primeira vez nos quadrinhos em:",
              alternatives: [Anwser(text: "1950"),
                             Anwser(text: "1955"),
                             Anwser(text: "1933"),
                             Anwser(text: "1930"),
                             Anwser(text: "1940", correct: true)]),

    Questions(question: "Quem ou o que foi o responsável por afundar o Titanic?",
              alternatives: [Anwser(text: "Ondas gigantes"),
                             Anwser(text: "Terroristas"),
                             Anwser(text: "O capitão"),
                             Anwser(text: "Uma baleia"),
                             Anwser(text: "Um iceberg", correct: true)]),

    Questions(question: "Qual dos consoles abaixo da Nintendo não é um portátil?",
              alternatives: [Anwser(text: "Nintendo 3DS"),
                             Anwser(text: "Gameboy SP"),
                             Anwser(text: "Gameboy Color"),
                             Anwser(text: "Nintendo DS"),
                             Anwser(text: "Nintendo 64", correct: true)]),

    Questions(question: "Quem é o principal protagonista da série Peaky Blinders?",
              alternatives: [Anwser(text: "Finn Burgess"),
                             Anwser(text: "Arthur Miller"),
                             Anwser(text: "Arthur Shelby"),
                             Anwser(text: "Steven Knight"),
                             Anwser(text: "Thomas Shelby", correct: true)]),

    Questions(question: "Qual o nome da cidade em que se passa Os Simpsons?",
              alternatives: [Anwser(text: "Sunnyvale"),
                             Anwser(text: "San Francisco"),
                             Anwser(text: "Albuquerque"),
                             Anwser(text: "Smallvile"),
                             Anwser(text: "Springfield", correct: true)]),

    Questions(question: "Qual o nome do filho de Homer Simpson?",
              alternatives: [Anwser(text: "Cid Moreira"),
                             Anwser(text: "Paul Walker"),
                             Anwser(text: "Michael Douglas"),
                             Anwser(text: "Ned Flanders"),
                             Anwser(text: "Bartholomew", correct: true)]),

    Questions(question: "Qual o sabor da bala gigante do desenho Du, Dudu e Edu?",
              alternatives: [Anwser(text: "Limão"),
                             Anwser(text: "Morango"),
                             Anwser(text: "Chocolate"),
                             Anwser(text: "Café"),
                             Anwser(text: "Caramelo", correct: true)]),

    Questions(question: "Qual o principal vilão em As Meninas Super Poderosas?",
              alternatives: [Anwser(text: "Hayaka"),
                             Anwser(text: "Lobo Bruxo"),
                             Anwser(text: "Macaco Azul"),
                             Anwser(text: "Cachorro Brabo"),
                             Anwser(text: "Macaco Louco", correct: true)])

]
